main/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin

from . import views, admin as app_admin


urlpatterns = [
    path('table/<int:pk>/', views.TableDetailView.as_view(), name='table-details'),
    path('table/<int:pk>/image.png', views.table_image, name='table-image'),
    path('table/autocreate', app_admin.autocreate_table, name='table-autocreate'),
]

admin.site.site_title = 'Расписания'
admin.site.site_header = 'Расписания'
admin.site.index_title = ''

timetable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]

main/models.py
from django.db import models
from model_utils.managers import InheritanceManager


class Building(models.Model):
    name = models.CharField(verbose_name='Название', max_length=16)
    odd_color = models.CharField(verbose_name='Цвет 1', max_length=7, default='#ffffff')
    even_color = models.CharField(verbose_name='Цвет 2', max_length=7, default='#ffffff')

    class Meta:
        verbose_name = 'корпус'
        verbose_name_plural = 'Корпусы'
        ordering = ['name']

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(verbose_name='Название', max_length=32)

    class Meta:
        verbose_name = 'отделение'
        verbose_name_plural = 'Отделения'
        ordering = ['name']

    def __str__(self):
        return self.name


# Дополнительные колонки, используются для разных видов наркозов
class ColumnType(models.Model):
    name = models.CharField(verbose_name='Название', max_length=8)

    class Meta:
        verbose_name = 'наркоз'
        verbose_name_plural = 'Наркозы'
        ordering = ['id']

    def __str__(self):
        return self.name


class Place(models.Model):
    enable = models.BooleanField(verbose_name='Показывать', default=True)
    template = models.BooleanField(verbose_name='Создавать каждый раз', default=False)


class Room(Place):
    building = models.ForeignKey(Building, verbose_name='Корпус', on_delete=models.SET_NULL, null=True)
    floor = models.IntegerField(verbose_name='Этаж')
    number = models.CharField(verbose_name='Номер', max_length=9, blank=True)
    department = models.ForeignKey(Department, verbose_name='Отделение', on_delete=models.SET_NULL,
                                   null=True, blank=True)
    # free_dept=True означает, что отделения будут задаваться в RoomLine, а Room.department не будет учитываться
    # операционная может быть закреплена за одним отделением, а может каждый день использоваться для разных отделений
    free_dept = models.BooleanField(verbose_name='Для разных отделений', default=False)

    class Meta:
        verbose_name = 'операционная'
        verbose_name_plural = 'Операционные'
        ordering = ['building__name', '-floor', 'number']

    ROMAN_LIT = ('0', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'XIII', 'XIV', 'XV')

    def floor_roman(self):
        return Room.ROMAN_LIT[self.floor] if 0 < self.floor < len(Room.ROMAN_LIT) else self.floor

    def __str__(self):
        return '{0}:{1} {2} {3}'.format(
            self.building.name if self.building else '', 
            self.floor_roman(), 
            ('№' if self.number.isdigit() else '') + self.number, 
            self.department.name if not self.free_dept and self.department else '')


class Chamber(Place):
    name = models.CharField(verbose_name='Название', max_length=32)

    class Meta:
        verbose_name = 'палата'
        verbose_name_plural = 'Палаты'
        ordering = ['name']

    def __str__(self):
        return self.name


class Employee(models.Model):
    name = models.CharField(verbose_name='ФИО', max_length=64)
    enable = models.BooleanField(verbose_name='Показывать', default=True)

    class Meta:
        verbose_name = 'работник'
        verbose_name_plural = 'Работники'
        ordering = ['name']

    def __str__(self):
        return self.name


class Doctor(Employee):

    class Meta:
        verbose_name = 'анестезиолог'
        verbose_name_plural = 'Анестезиологи'


class Resident(Employee):

    class Meta:
        verbose_name = 'ординатор'
        verbose_name_plural = 'Ординаторы'


class Nurse(Employee):

    class Meta:
        verbose_name = 'медсестра'
        verbose_name_plural = 'Медсестры'


class Table(models.Model):
    date = models.DateField(verbose_name='Дата')
    comment = models.TextField(verbose_name='Комментарий', blank=True)

    class Meta:
        verbose_name = 'расписание'
        verbose_name_plural = 'Расписания'
        ordering = ['-date']

    def column_types(self):
        return [{'id': cs['column_type__id'], 'name': cs['column_type__name']}
                for cs in ColumnValue.objects.filter(room_line__table=self)
                                             .values('column_type__id', 'column_type__name').distinct()]

    def __str__(self):
        return 'Расписание на ' + self.date.isoformat()


class Line(models.Model):
    objects = InheritanceManager()
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, verbose_name='Анестезиолог', on_delete=models.SET_NULL, 
                               null=True, blank=True, limit_choices_to={'enable': True})
    resident = models.ForeignKey(Resident, verbose_name='Ординатор', on_delete=models.SET_NULL, 
                                 null=True, blank=True, limit_choices_to={'enable': True})


class RoomLine(Line):
    room = models.ForeignKey(Room, verbose_name='Операционная', on_delete=models.SET_NULL,
                             null=True, limit_choices_to={'enable': True})
    link = models.ForeignKey(Line, related_name='linelink', verbose_name='Ссылка', 
                             on_delete=models.SET_NULL, null=True, blank=True)
    dept = models.ManyToManyField(Department, verbose_name='Отделения', blank=True)
    comment = models.CharField(verbose_name='Комментарий', max_length=256, blank=True)
    nurse = models.ForeignKey(Nurse, verbose_name='Медсестра', on_delete=models.SET_NULL, 
                              null=True, blank=True, limit_choices_to={'enable': True})
    begin_time = models.CharField(verbose_name='Начало', max_length=8, blank=True, null=True)
    oair = models.IntegerField(verbose_name='в ОАиР', blank=True, null=True)

    class Meta:
        verbose_name = 'назначение операционной'
        verbose_name_plural = 'Расписание операционных'
        ordering = ['room__building__name', '-room__floor', 'room__number']

    def dept_str(self):
        return ', '.join(dept.name for dept in self.dept.all()) if self.room.free_dept else \
            self.room.department.name if self.room.department else ''

    def columns(self):
        return {v.column_type.id: v.value for v in self.columnvalue_set.all()}

    def __str__(self):
        return '{0}:{1} {2} -> {3}'.format(
            self.room.building.name if self.room and self.room.building else '',
            self.room.floor_roman() if self.room else '',
            (('№' if self.room.number.isdigit() else '') + self.room.number) if self.room else '',
            self.doctor if self.doctor else '')


class ColumnValue(models.Model):
    column_type = models.ForeignKey(ColumnType, on_delete=models.SET_NULL, null=True, blank=True)
    room_line = models.ForeignKey(RoomLine, on_delete=models.CASCADE)
    value = models.CharField(max_length=8, blank=True)


class ChamberLine(Line):
    chamber = models.ManyToManyField(Chamber, verbose_name='Палаты', blank=True, limit_choices_to={'enable': True})

    class Meta:
        verbose_name = 'назначение для палаты'
        verbose_name_plural = 'Расписание для палат'
        ordering = ['chamber__name']

    def __str__(self):
        return '{0} -> {1}'.format('; '.join(ch.name for ch in self.chamber.all()), self.doctor if self.doctor else '')


class VacationLine(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, verbose_name='Врач', on_delete=models.SET_NULL, 
                                 null=True, limit_choices_to={'enable': True})

    class Meta:
        verbose_name = 'отпуск'
        verbose_name_plural = 'Отпуска'
        ordering = ['employee__name']

main/views.py
from django.views import generic
from django.http import FileResponse
from django.template.defaulttags import register
import imgkit
import operator

from .models import Table, RoomLine, ChamberLine, Building


MONTHS = ('января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 
          'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря')
ARROW_WIDTH = 16

IMAGE_FILENAME = 'image.png'


@register.filter
def key(dictionary, k):
    return dictionary.get(k)


class TableDetailView(generic.DetailView):
    model = Table
    image = False

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        date = data['table'].date
        data['datecap'] = '{0} {1}'.format(date.day, MONTHS[date.month - 1])

        # Строки передаются отдельно от всего расписания, чтобы разделить их на две категории (chamber / room)
        room_lines = [line for line in data['table'].line_set.select_subclasses() if isinstance(line, RoomLine)]
        room_lines.sort(key=lambda line: line.room.number)
        room_lines.sort(key=lambda line: line.room.floor, reverse=True)
        room_lines.sort(key=lambda line: line.room.building.name)

        chamber_lines = [line for line in data['table'].line_set.select_subclasses() if isinstance(line, ChamberLine)]
        chamber_lines.sort(key=lambda line: line.chamber.values()[0]['name'])

        # links = [(номер_начальной_строки, номер_конечной_строки, направление_назад_или_вперед), ...]
        lines_pk = [line.pk for line in room_lines] + [0] + [line.pk for line in chamber_lines]
        links = [(i, lines_pk.index(line.link.pk)) for i, line in enumerate(room_lines) if line.link]
        links = [(frm, to, False) if frm < to else (to, frm, True) for frm, to in links]
        links.sort(key=operator.itemgetter(0))
        if links:
            classes = link_table(links, len(lines_pk))
            data['comment_indent'] = max(cl[1] for ln in classes for cl in ln)
            # Запись классов для стрелочек в строки расписания
            for i, cls in enumerate(classes):
                if i < len(room_lines):
                    room_lines[i].cls = cls
                elif i == len(room_lines):
                    data['blank_cls'] = cls
                elif i > len(room_lines):
                    chamber_lines[i - len(room_lines) - 1].cls = cls

        data['room_lines'] = room_lines
        data['chamber_lines'] = chamber_lines
        data['buildings'] = Building.objects.all()
        data['column_types'] = data['table'].column_types()
        data['image'] = self.image

        return data


def link_table(links, total):
    # поиск свободного места для стрелочки (чтобы они не накладывались)
    cols = []
    for link_from, link_to, rev in links:
        free_col = 1
        for j, (col, frm, to, _) in enumerate(cols):
            if link_from < to <= link_to:
                free_col = max(free_col, col + 1)
            elif frm < link_from and link_to < to and col == free_col:
                free_col = col
                cols[j][0] = col + 1
        cols.append([free_col, link_from, link_to, rev])

    # преобразование полученного в css-классы и ширину (вынос) стрелочки
    classes = [[] for i in range(total)]
    for col, frm, to, rev in cols:
        classes[frm].append(('out', col * ARROW_WIDTH))
        for i in range(frm + 1, to):
            classes[i].append(('down', col * ARROW_WIDTH))
        classes[to].append(('in', col * ARROW_WIDTH))
        if rev:
            classes[frm].append(('arrow back', 0))
        else:
            classes[to].append(('arrow forw', 0))
    return classes


def table_image(request, pk):
    html_response = TableDetailView.as_view(image=True)(request, pk=pk)
    table_date = html_response.context_data['table'].date
    html_response.render()
    content = str(html_response.content, 'utf-8')
    imgkit.from_string(content, IMAGE_FILENAME)
    response = FileResponse(open(IMAGE_FILENAME, 'rb'))
    response['Content-Disposition'] = 'attachment; filename=table-{0}.png'.format(table_date.strftime('%Y-%m-%d'))
    return response

main/templates/main/table_detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />

<style type="text/css">
body {
    font-family: Arial, Helvetica, sans-serif;
    margin: 0px;
}
table {
    width: 1280px;
    height: 720px;
    border-spacing: 1px 0;
    border-collapse: separate;
}
h1 {
    font-size: 32px;
}
th {
    background: #ccc;
}
th.space, td.space, th.cap {
    background: #fff;
}
th.cap {
    font-size: 24px;
}
tr {
    text-align: center;
    font-size: 19px;
}
tr:nth-child(even) {
    background: #eee;
}
tr.space {
    height: 19px;
    background: #fff;
}
td.comment {
    background: #fff;
    text-align: left;
    font-size: 15px;
}
td.supercomment {
    text-align: left;
    font-size: 15px;
}
td.link {
    position: relative;
    background: #fff;
}
div.in, div.down, div.out {
    position: absolute;
    left: 0;
    width: 16px;
    border: 2px solid black;
}
div.out {
    border-width: 2px 2px 0 0;
    border-radius: 0 4px 0 0;
    bottom: 0;
    height: 7px;
}
div.down {
    border-width: 0 2px 0 0;
    top: 0;
    height: 100%;
}
div.in {
    border-width: 0 2px 2px 0;
    border-radius: 0 0 4px 0;
    top: 0;
    height: 7px;
}
div.arrow {
    position: absolute;
    left: -1px;
    width: 0;
    height: 0;
    border-top: 5px solid transparent;
    border-bottom: 5px solid transparent;
    border-right: 10px solid black;
}
div.arrow.forw {
    top: 3px;
}
div.arrow.back {
    bottom: 3px;
}

{% for build in buildings %}
tr:nth-child(even).build-{{build.pk}} {
    background: {{build.even_color}};
}
tr:nth-child(odd).build-{{build.pk}} {
    background: {{build.odd_color}};
}
{% endfor %}

{% if image %}
table {
    width: 1920px;
    height: 1080px;
}
h1 {
    font-size: 48px;
}
th.cap {
    font-size: 36px;
    padding: 8px 0;
}
th {
    padding: 4px 0;
}
tr {
    font-size: 28px;
}
tr.space {
    height: 28px;
}
td.comment {
    font-size: 22px;
}
td.supercomment {
    font-size: 22px;
}
{% endif %}
</style>

</head>
<body>

<table>
<thead>
<tr>
  <th colspan="{{column_types|length|add:'9'}}" class="cap">Расписание наркозов на {{ datecap }}</th>
  <th colspan="2" class="space"></th>
</tr>
<tr>
  <th>Блок</th>
  <th>Начало</th>
  <th>Этаж</th>
  <th>Опер.</th>
  <th>Отделение</th>
  {% for coltype in column_types %}
    <th>{{ coltype.name }}</th>
  {% endfor %}
  <th>Анестезиолог</th>
  <th>Ординатор</th>
  <th>Медсестра</th>
  <th>в ОАиР</th>
  <th class="space" style="width: {{ comment_indent|add:'8' }}px;"></th>
  <th class="space"></th>
</tr>
</thead>
<tbody>

{% for line in room_lines %}
<tr class="rooms build-{{line.room.building.pk}}">
  <td class="building">{% ifchanged line.room.building.name %}{{ line.room.building.name }}{% endifchanged %}</td>
  <td class="time">{{ line.begin_time|default:'' }}</td>
  <td class="floor">{{ line.room.floor_roman }}</td>
  <td class="room">{{ line.room.number }}</td>
  <td class="dept">{{ line.dept_str }}</td>
  {% for coltype in column_types %}
    <td>{{ line.columns|key:coltype.id|default:'' }}</td>
  {% endfor %}
  <td class="doctor">{{ line.doctor|default:'' }}</td>
  <td class="resident">{{ line.resident|default:'' }}</td>
  <td class="nurse">{{ line.nurse|default:'' }}</td>
  <td class="oair">{{ line.oair|default:'' }}</td>
  <td class="link">{% for cl in line.cls %}<div class="{{ cl.0 }}" style="width: {{ cl.1 }}px;"></div>{% endfor %}</td>
  <td class="comment">{{ line.comment }}</td>
</tr>
{% endfor %}

<tr class="space">
  <td colspan="{{column_types|length|add:'9'}}"></td>
  <td class="link">{% for cl in blank_cls %}<div class="{{ cl.0 }}" style="width: {{ cl.1 }}px;"></div>{% endfor %}</td>
  <td class="supercomment" rowspan="{{ chamber_lines|length|add:'3' }}">{{ table.comment|linebreaks }}</td>
</tr>

{% for line in chamber_lines %}
<tr class="chambers">
  <td colspan="{{column_types|length|add:'5'}}" class="room">{% for ch in line.chamber.all %}{{ ch.name }}{% if not forloop.last %} + {% endif %}{% endfor %}</td>
  <td class="doctor">{{ line.doctor|default:'' }}</td>
  <td class="resident">{{ line.resident|default:'' }}</td>
  <td class="nurse"></td>
  <td class="oair"></td>
  <td class="link">{% for cl in line.cls %}<div class="{{ cl.0 }}" style="width: {{ cl.1 }}px;"></div>{% endfor %}</td>
</tr>
{% endfor %}

<tr class="space"><td colspan="{{column_types|length|add:'11'}}"></td></tr>

<tr class="vacations">
  <td colspan="2">Домой</td>
  <td colspan="{{column_types|length|add:'7'}}" class="doctor">
  {% for line in table.vacationline_set.all %}
    {{ line.employee.name }}{% if not forloop.last %}, {% endif %}
  {% endfor %}
  </td>
  <td colspan="2" class="space"></td>
</tr>

</tbody>
</table>

</body>
</html>